### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by stewsters** [seniorjoinu/prodigy#1]
Could you post an example project that uses this?  

I tried copying the example on the readme but I am having some trouble with Serializeable being internal in kotlin.io and the expression 'protocol' cannot be invoked as a function.  I suspect I am importing the wrong version of something, but am not sure what.

**Comment by seniorjoinu** [comment]
I'm sorry for so long time not answering - holidays in Russia c:

`Serializable` should be imported nicely because it's from `java.io`

Can you please provide more details? Like what do you put in `build.gradle`.

I'm working right now on `Kademlia` implementation using `prodigy` to provide some useful example. Hope it will be ready in a day or two.

**Comment by seniorjoinu** [comment]
Btw, you can clone this repo and start the test `prodigy/src/test/kotlin/net/joinu/prodigy/ExampleTest.kt`

**Comment by seniorjoinu** [comment]
So, yes. I've managed to bring `Kademlia`'s implementation to some working state.
It uses `prodigy 0.1.1` - here is the code - https://github.com/seniorjoinu/prodigy-kademlia-routing

There is no annotation right now, but what you're looking for is in [here](https://github.com/seniorjoinu/prodigy-kademlia-routing/blob/master/build.gradle), [here](https://github.com/seniorjoinu/prodigy-kademlia-routing/blob/master/src/main/kotlin/net/joinu/kademlia/KademliaRoutingProtocol.kt) and  [here](https://github.com/seniorjoinu/prodigy-kademlia-routing/blob/master/src/test/kotlin/net/joinu/kademlia/ClusterTest.kt)

**Comment by seniorjoinu** [comment]
I've also added some kind of tutorial to the `prodigy`'s README.md. Take a look.

**Comment by stewsters** [comment]
So it does work from the repo.  I took a look at it and got it to run on the test project I had by adding this function to my code:

`fun protocol(name: String, init: Protocol.() -> Unit): Protocol {
    val protocol = Protocol(name)
    protocol.init()
    return protocol
}`

For whatever reason it was not getting picked up from jitpack.  Code compiles fine now, but is missing a lib for linux.  Ill post that on https://github.com/seniorjoinu/wirehair-wrapper, as I think thats where you will add them.
